### ISSUE TITLE
Multi-select Arrow Float 1.3.2

### ISSUE THREAD

**Issue by ssanders** [paramquery/select#19]
I have jQuery to just add a down arrow to a multi-select.
```js
jq("[name='OngoingServices_worktypes[] '").prepend(
	'<span class=\"ui-icon ui-icon-triangle-1-s\"></span>'
);
```
I updated 1.2 to 1.3.2. Now arrow and text are on two lines. I fixed it though with this CSS.
```css
.ui-icon-triangle-1-s {
	float: right;
}
```
